- name: Hello World Sample
  hosts: all
  vars:
    nginx_private_key: "{{ lookup('cyberark.conjur.conjur_variable', 'cd/ansible/secrets/nginx_private_key', validate_certs=false) }}"
    machine:
      username: '{{ ansible_user }}'
      password: '{{ ansible_password }}'
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - debug:
        var: machine    
    - name: Lookup variable in Conjur
      debug: 
        msg: "{{ nginx_private_key }}"
