- name: Hello World Sample
  hosts: localhost
  vars:
  machine:
    username: '{{ ansible_user }}'
    password: '{{ ansible_password }}'
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - debug:
        var: machine    
