- name: Hello World Sample
  hosts: nginx-host
  vars:
    machine:
      username: '{{ ansible_user }}'
      password: '{{ ansible_password }}'
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Display Username and Password
      debug:
        msg: "Username: {{ machine.username }}, Password: {{ machine.password }}" 
