- name: nginx setup
  hosts: nginx-host
  become: true
  tasks:      
    - name: Installs nginx web server
      yum: pkg=nginx state=present update_cache=true
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started
- name: Gathering service facts
  service_facts:

- name: Get facts
  debug:
    msg:
      - "{{ ansible_facts.services['nginx'].status }}"
