- name: nginx setup
  hosts: nginx-host
  become: true
  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
      
    - name: Installs nginx web server
      yum: pkg=nginx state=present update_cache=true
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started
