- name: nginx setup
  hosts: nginx-host
  become: true
  tasks:      
    - name: Installs nginx web server
      yum: pkg=nginx state=latest
      notify:
        - start nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
      sudo: yes
      
    - name: Get facts
      debug:
        msg:
          - "{{ ansible_facts.services['nginx'].status }}"
